name: Node.js CI

on:
  push:
    branches:
      - develop
jobs:
  build:
  createPullRequest:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'New release'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: 'new release'
          title: 'new release'
          labels: automerge
          assignees: lisomartinez
          reviewers: lisomartinez
          branch: example-patches
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow-2
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
